#
# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# Install Monasca Ceilometer (For Ocata and Pike)
# ===============================================
# This is a play which which overlays ceilometer source code
# with monasca-ceilometer code.
# Monasca-ceilometer code contains Ceilometer publisher and
# storage driver for Monasca.
#
# Steps:
#
# 1.) Install monasca-ceilometer venv
# 2.) Copy contents from monasca-ceilometer venv to ceilometer venv
# 3.) Update ceilometer's egg-info/entry_points.txt and add
#     monasca publisher and monasca storage driver entry_points.txt
#
# IMPORTANT NOTE:
#
# This was specially created to deploy Ceilometer with Monasca Ceilometer
# when using existing venv building mechanism in ardana.
#
# For Pike with the new RPM to venv generation process
# we will have to remove this playbook.
---
- name: _CEI-CMN | _install_monasca_ceilometer | Installing Monasca Ceilometer
  become: yes
  install_package:
    name: monasca_ceilometer
    service: monasca-ceilometer
    state: present
  register: ardana_notify_monasca_ceilometer_install_result

- name: _CEI-CMN | _install_monasca_ceilometer | set service directories install
  set_fact:
    monasca_ceilometer_etc_dir: |
      "{{ 'monasca-ceilometer' |
        config_dir(ardana_notify_monasca_ceilometer_install_result.version) }}"
    monasca_ceilometer_conf_dir: |
      "{{ 'monasca-ceilometer' |
        config_dir(ardana_notify_monasca_ceilometer_install_result.version) }}\
      /nova"
    monasca_ceilometer_bin_dir: |
      "{{ 'monasca-ceilometer' |
        bin_dir(ardana_notify_monasca_ceilometer_install_result.version) }}"

- name: _CEI-CMN | _install_monasca_ceilometer | Create directories
  become: yes
  file:
    state: directory
    path: "{{ ceilometer_bin_dir }}/../lib/python2.7/\
          site-packages/ceilometer/{{ item }}"
    mode: 0755
  with_items:
    - "ceilosca_mapping"
    - "ceilosca_mapping/data"
    - "publisher"
    - "storage"
    - "api"

- name: _CEI-CMN | _install_monasca_ceilometer | Copy files to ceilometer
  become: yes
  command: "cp {{ monasca_ceilometer_bin_dir }}/../lib/python2.7/\
            site-packages/ceilosca/ceilometer/{{ item }} \
            {{ ceilometer_bin_dir }}/../lib/python2.7/\
            site-packages/ceilometer/{{ item }}"
  with_items:
    - "monasca_client.py"
    - "monasca_ceilometer_opts.py"
    - "opts.py"
    - "service.py"
    - "api/health.py"
    - "ceilosca_mapping/__init__.py"
    - "ceilosca_mapping/ceilometer_static_info_mapping.py"
    - "ceilosca_mapping/ceilosca_mapping.py"
    - "ceilosca_mapping/data/ceilometer_static_info_mapping.yaml"
    - "ceilosca_mapping/data/ceilosca_mapping.yaml"
    - "publisher/monasca_data_filter.py"
    - "publisher/monclient.py"
    - "storage/impl_monasca.py"

- name: _CEI-CMN | _install_monasca_ceilometer | Find .egg directories
  shell: >
    ls {{ ceilometer_bin_dir }}/../lib/python2.7/site-packages/
    | grep 'ceilometer-'
  register: ceilometer_egg_directories_result

- name: _CEI-CMN | _install_monasca_ceilometer | remove monasca publisher
  become: yes
  lineinfile:
    name: "{{ ceilometer_bin_dir }}/../lib/python2.7/\
          site-packages/{{ item }}/entry_points.txt"
    state: absent
    regexp: 'monasca = ceilometer.publisher.monclient:MonascaPublisher'
  with_items:
    ceilometer_egg_directories_result.stdout_lines

- name: _CEI-CMN | _install_monasca_ceilometer | add monasca publisher
  become: yes
  lineinfile:
    name: "{{ ceilometer_bin_dir }}/../lib/python2.7/\
          site-packages/{{ item }}/entry_points.txt"
    state: present
    regexp: '\[ceilometer.sample.publisher\]'
    line: >-
      [ceilometer.sample.publisher]\nmonasca =
      ceilometer.publisher.monclient:MonascaPublisher
  with_items:
    ceilometer_egg_directories_result.stdout_lines

- name: _CEI-CMN | _install_monasca_ceilometer | remove storage driver
  become: yes
  lineinfile:
    name: "{{ ceilometer_bin_dir }}/../lib/python2.7/\
          site-packages/{{ item }}/entry_points.txt"
    state: absent
    regexp: 'monasca = ceilometer.storage.impl_monasca:Connection'
  with_items:
    ceilometer_egg_directories_result.stdout_lines

- name: _CEI-CMN | _install_monasca_ceilometer | add storage driver
  become: yes
  lineinfile:
    name: "{{ ceilometer_bin_dir }}/../lib/python2.7/\
          site-packages/{{ item }}/entry_points.txt"
    state: present
    regexp: '\[ceilometer.metering.storage\]'
    line: >-
      [ceilometer.metering.storage]\nmonasca =
      ceilometer.storage.impl_monasca:Connection
  with_items:
    ceilometer_egg_directories_result.stdout_lines