#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: ../../_CEI-CMN/tasks/configure.yml
  vars:
    ceilometer_conf_dir: "{{ ceilometer_nag_conf_dir }}"

- name: CEI-NAG | configure | Register ceilometer nag restart
  command: /bin/true
  register: ardana_notify_ceilometer_nag_restart_required
  when: ardana_notify_ceilometer_common_restart_required.changed


- include: ../../_CEI-CMN/tasks/_write_conf.yml
  src: "../../CEI-NAG/templates/agent-notification.conf.j2"
  dest: "{{ ceilometer_nag_conf_dir }}/agent-notification.conf"

- name: CEI-NAG | configure | configure agent-notification.conf
  command: /bin/true
  register: ardana_notify_ceilometer_nag_restart_required
  when: write_conf_result.changed

- include: ../../_CEI-CMN/tasks/_write_conf.yml
  src: "../../CEI-NAG/templates/agent-notification-logging.conf.j2"
  dest: "{{ ceilometer_nag_conf_dir }}/agent-notification-logging.conf"

- name: CEI-NAG | configure | configure agent-notification-logging.conf
  command: /bin/true
  register: ardana_notify_ceilometer_nag_restart_required
  when: write_conf_result.changed

- include: ../../_CEI-CMN/tasks/_write_conf.yml
  src: "../../CEI-NAG/templates/meters.yaml.j2"
  dest: "{{ ceilometer_nag_conf_dir }}/meters.yaml"

- name: CEI-NAG | configure | configure meters.yaml
  command: /bin/true
  register: ardana_notify_ceilometer_nag_restart_required
  when: write_conf_result.changed

- include: pipeline_configure.yml

- name: CEI-NAG | configure | create ceilometer-agent-notification log
  become: yes
  file:
    path: "{{ ceilometer_log_dir }}/{{ item }}"
    state: touch
    owner: "{{ ceilometer_user }}"
    group: "{{ ceilometer_log_group }}"
    mode: 0640
  with_items:
    - ceilometer-agent-notification.log
    - ceilometer-agent-notification-json.log
  register: ardana_notify_ceilometer_nag_restart_required

# With 'enable' SLES systemctl fails, claiming 'Too many levels of symbolic
# links', if service is already enabled and systemd unit file is symlink.
# So reenable is the suggested option.
- name: CEI-NAG | configure | Enable the ceilometer notifiation agent
    services to start on boot
  become: yes
  command: systemctl reenable ceilometer-agent-notification
  register: ardana_notify_ceilometer_nag_restart_required
